### ISSUE TITLE
Handling error response on auth request

### ISSUE THREAD

**Issue by ujjwalchadha** [dunhor/WinAuth#1]
Problem/Repro:
Give a mismatching redirect URI to AuthRequestParams
```
var requestParams = AuthRequestParams.CreateForAuthorizationCodeRequest("client-id", new Uri("incorrect uri"));
var res = await AuthManager.InitiateAuthRequestAsync(new Uri("https://github.com/login/oauth/authorize"), requestParams);
```
The return response uri is: `ujchadha.oauthconsumptionsample://gitauth/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=lXC4ulvaKZOGgoTsUUX-TJlx8TZNYL2uU4MdOoqH4NY`

Expectation: This should throw an exception upon detecting the "error" param in the response
Actual: No exception. The res.Response object is null and the res.ResponseUri is the value printed above

**Comment by dunhor** [comment]
That's expected. It uses an error object to communicate richer error information (you cannot do this through exception). It is a common WinRT design pattern to have "result" objects with success/error objects attached to them

**Comment by ujjwalchadha** [comment]
Sure, but shouldn't there be more than just the response uri indicating that there is an error?

**Comment by dunhor** [comment]
I'm not sure what you mean? What else would there be?

**Comment by ujjwalchadha** [comment]
Nvm. I didn't see the res.Failure property which correctly reports the error. If there's no exception, this seems right.
